addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"           % "1.3.5")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.7")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.3.1")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"            % "2.1.1")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.6.0")
addCompilerPlugin("com.olegpy"           %% "better-monadic-for" % "0.3.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-missinglink"     % "0.2.0")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"      % "1.5.0")
