addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"           % "1.4.10")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.20")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.3.1")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"            % "2.2.24")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.6.1")
addCompilerPlugin("com.olegpy"           %% "better-monadic-for" % "0.3.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-missinglink"     % "0.3.2")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"      % "1.5.6")
