addSbtPlugin("com.dwijnand"       % "sbt-dynver"   % "3.0.0")
addSbtPlugin("com.dwijnand"       % "sbt-travisci" % "1.1.1")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt" % "1.6.0-RC3")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.3.3")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix" % "0.9.1")
